# Generated by Django 4.0.6 on 2022-08-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_customer_address_customer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='blood_suger_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='complaints',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
