# Generated by Django 4.0.6 on 2022-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_alter_customer_blood_suger_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='blood_pressure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='genral_exams',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pulse',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
