# Generated by Django 4.0.6 on 2022-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_alter_customer_address_alter_customer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
