# Generated by Django 4.0.6 on 2022-08-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgener]')], max_length=1, null=True),
        ),
    ]
