# Generated by Django 4.0.6 on 2022-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0016_alter_customer_options_alter_treatment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='treatment',
            field=models.ManyToManyField(to='reg.treatment'),
        ),
    ]
