# Generated by Django 4.0.6 on 2022-08-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0017_customer_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='treatment',
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.treatment'),
        ),
    ]
