# Generated by Django 4.0.6 on 2022-08-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0018_remove_customer_treatment_customer_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='treatment',
        ),
        migrations.AddField(
            model_name='customer',
            name='details_1',
            field=models.CharField(default=2, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='details_2',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='details_3',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='details_4',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='details_5',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='details_6',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_name_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_name_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_name_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_name_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_name_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_name_6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_type_1',
            field=models.CharField(choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_type_2',
            field=models.CharField(choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_type_3',
            field=models.CharField(choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_type_4',
            field=models.CharField(choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_type_5',
            field=models.CharField(choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_type_6',
            field=models.CharField(choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='units_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='units_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='units_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='units_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='units_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='units_6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='genral_exams',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
