# Generated by Django 4.0.6 on 2022-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0020_alter_customer_treatment_type_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='blood_suger_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='complaints',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details_1',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details_2',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details_3',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details_4',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details_5',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details_6',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='genral_exams',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pulse',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='temprature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_name_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_name_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_name_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_name_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_name_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_type_1',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_type_2',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_type_3',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_type_4',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_type_5',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='treatment_type_6',
            field=models.CharField(blank=True, choices=[('Injection', 'Injection'), ('Medicines/Capsules', 'Medicines/Capsules'), ('Syrup', 'Syrup'), ('Tube', 'Tube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='units_6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
